# Generated by Django 2.0.4 on 2018-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('seals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='materials',
            field=models.ManyToManyField(to='materials.Material'),
        ),
    ]
