# Generated by Django 2.0.4 on 2018-04-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconographic_elements', '0001_initial'),
        ('seals', '0002_seal_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='iconographic_elements',
            field=models.ManyToManyField(to='iconographic_elements.IconographicElement'),
        ),
    ]
