# Generated by Django 2.0.4 on 2018-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
        ('seals', '0003_seal_iconographic_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='scenes',
            field=models.ManyToManyField(to='scenes.Scene'),
        ),
    ]
