# Generated by Django 2.0.4 on 2018-04-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
        ('seals', '0005_seal_art_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='periods',
            field=models.ManyToManyField(to='periods.Period'),
        ),
    ]
