# Generated by Django 2.0.4 on 2018-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0006_seal_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='art_styles',
            field=models.ManyToManyField(blank=True, to='art_styles.ArtStyle'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='iconographic_elements',
            field=models.ManyToManyField(blank=True, to='iconographic_elements.IconographicElement'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='materials',
            field=models.ManyToManyField(blank=True, to='materials.Material'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='periods',
            field=models.ManyToManyField(blank=True, to='periods.Period'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='scenes',
            field=models.ManyToManyField(blank=True, to='scenes.Scene'),
        ),
    ]
