# Generated by Django 2.0.4 on 2018-04-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        ('seals', '0007_allow_blank_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='publications',
            field=models.ManyToManyField(blank=True, to='publications.Publication'),
        ),
    ]
