# Generated by Django 2.0.4 on 2018-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('seals', '0009_seal_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='languages',
            field=models.ManyToManyField(blank=True, to='languages.Language'),
        ),
    ]
