# Generated by Django 2.0.4 on 2018-04-24 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_types', '0001_initial'),
        ('seals', '0010_seal_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='seal',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_types.ObjectType'),
        ),
    ]
