# Generated by Django 2.0.4 on 2018-04-24 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seals', '0011_seal_object_type'),
        ('materials', '0001_initial'),
        ('languages', '0001_initial'),
        ('object_types', '0001_initial'),
        ('texts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cdli_number', models.CharField(blank=True, max_length=255)),
                ('p_number', models.CharField(blank=True, max_length=255)),
                ('museum_number', models.CharField(blank=True, max_length=255)),
                ('accession_number', models.CharField(blank=True, max_length=255)),
                ('publication_number', models.CharField(blank=True, max_length=255)),
                ('collection', models.CharField(blank=True, max_length=255)),
                ('length', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('surface_preservation', models.IntegerField(blank=True, choices=[(0, 'Poor'), (1, 'Fair'), (2, 'Good'), (3, 'Excellent')], null=True)),
                ('condition', models.TextField(blank=True)),
                ('physical_remarks', models.TextField(blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_remarks', models.TextField(blank=True)),
                ('excavation_number', models.CharField(blank=True, max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, to='languages.Language')),
                ('materials', models.ManyToManyField(blank=True, to='materials.Material')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_types.ObjectType')),
                ('periods', models.ManyToManyField(blank=True, to='periods.Period')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seals.Seal')),
                ('texts', models.ManyToManyField(blank=True, to='texts.Text')),
            ],
        ),
    ]
