# Generated by Django 2.0.4 on 2018-04-25 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('seals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='seal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='seals.Seal'),
        ),
    ]
