# Generated by Django 2.0.3 on 2018-03-27 02:01

from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('cdli_number', models.CharField(blank=True, max_length=255)),
                ('museum_number', models.CharField(blank=True, max_length=255)),
                ('accession_number', models.CharField(blank=True, max_length=255)),
                ('publication_number', models.CharField(blank=True, max_length=255)),
                ('collection', models.CharField(blank=True, max_length=255)),
                ('height', django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True)),
                ('thickness', django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True)),
                ('width', django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True)),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True)),
                ('drill_hole_diameter', django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True)),
                ('perforations', models.CharField(blank=True, max_length=255)),
                ('surface_preservation', models.IntegerField(blank=True, choices=[(0, 'Poor'), (1, 'Fair'), (2, 'Good'), (3, 'Excellent')], null=True)),
                ('condition', models.TextField(blank=True)),
                ('is_recarved', models.NullBooleanField()),
                ('physical_remarks', models.TextField(blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_remarks', models.TextField(blank=True)),
                ('excavation_number', models.CharField(blank=True, max_length=255)),
                ('design', models.CharField(blank=True, choices=[('FIGURATIVE', 'Figurative'), ('GEOMETRIC', 'Geometric')], max_length=10)),
                ('design_remarks', models.TextField(blank=True)),
            ],
        ),
    ]
