# Generated by Django 2.0.4 on 2018-04-25 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historical_persons', '0001_initial'),
        ('impressions', '0001_initial'),
        ('seals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_relationships', to=settings.AUTH_USER_MODEL)),
                ('historical_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_relationships', to='historical_persons.HistoricalPerson')),
                ('impression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_relationships', to='impressions.Impression')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_relationships', to='seals.Seal')),
            ],
        ),
    ]
